"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class ServerLiveRequest(google.protobuf.message.Message):
    """
    ServerLive messages.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___ServerLiveRequest: typing_extensions.TypeAlias = ServerLiveRequest

@typing.final
class ServerLiveResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    LIVE_FIELD_NUMBER: builtins.int
    live: builtins.bool
    """True if the inference server is live, false if not live."""
    def __init__(
        self,
        *,
        live: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["live", b"live"]) -> None: ...

Global___ServerLiveResponse: typing_extensions.TypeAlias = ServerLiveResponse

@typing.final
class ServerReadyRequest(google.protobuf.message.Message):
    """
    ServerReady messages.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___ServerReadyRequest: typing_extensions.TypeAlias = ServerReadyRequest

@typing.final
class ServerReadyResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    READY_FIELD_NUMBER: builtins.int
    ready: builtins.bool
    """True if the inference server is ready, false if not ready."""
    def __init__(
        self,
        *,
        ready: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["ready", b"ready"]) -> None: ...

Global___ServerReadyResponse: typing_extensions.TypeAlias = ServerReadyResponse

@typing.final
class ModelReadyRequest(google.protobuf.message.Message):
    """
    ModelReady messages.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    VERSION_FIELD_NUMBER: builtins.int
    name: builtins.str
    """The name of the model to check for readiness."""
    version: builtins.str
    """The version of the model to check for readiness. If not given the
    server will choose a version based on the model and internal policy.
    """
    def __init__(
        self,
        *,
        name: builtins.str = ...,
        version: builtins.str = ...,
    ) -> None: ...
    def ClearField(
        self, field_name: typing.Literal["name", b"name", "version", b"version"]
    ) -> None: ...

Global___ModelReadyRequest: typing_extensions.TypeAlias = ModelReadyRequest

@typing.final
class ModelReadyResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    READY_FIELD_NUMBER: builtins.int
    ready: builtins.bool
    """True if the model is ready, false if not ready."""
    def __init__(
        self,
        *,
        ready: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["ready", b"ready"]) -> None: ...

Global___ModelReadyResponse: typing_extensions.TypeAlias = ModelReadyResponse

@typing.final
class ServerMetadataRequest(google.protobuf.message.Message):
    """
    ServerMetadata messages.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___ServerMetadataRequest: typing_extensions.TypeAlias = ServerMetadataRequest

@typing.final
class ServerMetadataResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    VERSION_FIELD_NUMBER: builtins.int
    EXTENSIONS_FIELD_NUMBER: builtins.int
    name: builtins.str
    """The server name."""
    version: builtins.str
    """The server version."""
    @property
    def extensions(
        self,
    ) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]:
        """The extensions supported by the server."""

    def __init__(
        self,
        *,
        name: builtins.str = ...,
        version: builtins.str = ...,
        extensions: collections.abc.Iterable[builtins.str] | None = ...,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "extensions", b"extensions", "name", b"name", "version", b"version"
        ],
    ) -> None: ...

Global___ServerMetadataResponse: typing_extensions.TypeAlias = ServerMetadataResponse

@typing.final
class ModelMetadataRequest(google.protobuf.message.Message):
    """
    ModelMetadata messages.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    VERSION_FIELD_NUMBER: builtins.int
    name: builtins.str
    """The name of the model."""
    version: builtins.str
    """The version of the model to check for readiness. If not given the
    server will choose a version based on the model and internal policy.
    """
    def __init__(
        self,
        *,
        name: builtins.str = ...,
        version: builtins.str = ...,
    ) -> None: ...
    def ClearField(
        self, field_name: typing.Literal["name", b"name", "version", b"version"]
    ) -> None: ...

Global___ModelMetadataRequest: typing_extensions.TypeAlias = ModelMetadataRequest

@typing.final
class ModelMetadataResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class TensorMetadata(google.protobuf.message.Message):
        """Metadata for a tensor."""

        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        @typing.final
        class ParametersEntry(google.protobuf.message.Message):
            DESCRIPTOR: google.protobuf.descriptor.Descriptor

            KEY_FIELD_NUMBER: builtins.int
            VALUE_FIELD_NUMBER: builtins.int
            key: builtins.str
            @property
            def value(self) -> Global___InferParameter: ...
            def __init__(
                self,
                *,
                key: builtins.str = ...,
                value: Global___InferParameter | None = ...,
            ) -> None: ...
            def HasField(
                self, field_name: typing.Literal["value", b"value"]
            ) -> builtins.bool: ...
            def ClearField(
                self, field_name: typing.Literal["key", b"key", "value", b"value"]
            ) -> None: ...

        NAME_FIELD_NUMBER: builtins.int
        DATATYPE_FIELD_NUMBER: builtins.int
        SHAPE_FIELD_NUMBER: builtins.int
        PARAMETERS_FIELD_NUMBER: builtins.int
        name: builtins.str
        """The tensor name."""
        datatype: builtins.str
        """The tensor data type."""
        @property
        def shape(
            self,
        ) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[
            builtins.int
        ]:
            """The tensor shape. A variable-size dimension is represented
            by a -1 value.
            """

        @property
        def parameters(
            self,
        ) -> google.protobuf.internal.containers.MessageMap[
            builtins.str, Global___InferParameter
        ]:
            """Optional default parameters for input.
            NOTE: This is an extension to the standard
            """

        def __init__(
            self,
            *,
            name: builtins.str = ...,
            datatype: builtins.str = ...,
            shape: collections.abc.Iterable[builtins.int] | None = ...,
            parameters: (
                collections.abc.Mapping[builtins.str, Global___InferParameter] | None
            ) = ...,
        ) -> None: ...
        def ClearField(
            self,
            field_name: typing.Literal[
                "datatype",
                b"datatype",
                "name",
                b"name",
                "parameters",
                b"parameters",
                "shape",
                b"shape",
            ],
        ) -> None: ...

    @typing.final
    class ParametersEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        @property
        def value(self) -> Global___InferParameter: ...
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: Global___InferParameter | None = ...,
        ) -> None: ...
        def HasField(
            self, field_name: typing.Literal["value", b"value"]
        ) -> builtins.bool: ...
        def ClearField(
            self, field_name: typing.Literal["key", b"key", "value", b"value"]
        ) -> None: ...

    NAME_FIELD_NUMBER: builtins.int
    VERSIONS_FIELD_NUMBER: builtins.int
    PLATFORM_FIELD_NUMBER: builtins.int
    INPUTS_FIELD_NUMBER: builtins.int
    OUTPUTS_FIELD_NUMBER: builtins.int
    PARAMETERS_FIELD_NUMBER: builtins.int
    name: builtins.str
    """The model name."""
    platform: builtins.str
    """The model's platform. See Platforms."""
    @property
    def versions(
        self,
    ) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]:
        """The versions of the model available on the server."""

    @property
    def inputs(
        self,
    ) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[
        Global___ModelMetadataResponse.TensorMetadata
    ]:
        """The model's inputs."""

    @property
    def outputs(
        self,
    ) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[
        Global___ModelMetadataResponse.TensorMetadata
    ]:
        """The model's outputs."""

    @property
    def parameters(
        self,
    ) -> google.protobuf.internal.containers.MessageMap[
        builtins.str, Global___InferParameter
    ]:
        """Optional default parameters for the request / response.
        NOTE: This is an extension to the standard
        """

    def __init__(
        self,
        *,
        name: builtins.str = ...,
        versions: collections.abc.Iterable[builtins.str] | None = ...,
        platform: builtins.str = ...,
        inputs: (
            collections.abc.Iterable[Global___ModelMetadataResponse.TensorMetadata]
            | None
        ) = ...,
        outputs: (
            collections.abc.Iterable[Global___ModelMetadataResponse.TensorMetadata]
            | None
        ) = ...,
        parameters: (
            collections.abc.Mapping[builtins.str, Global___InferParameter] | None
        ) = ...,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "inputs",
            b"inputs",
            "name",
            b"name",
            "outputs",
            b"outputs",
            "parameters",
            b"parameters",
            "platform",
            b"platform",
            "versions",
            b"versions",
        ],
    ) -> None: ...

Global___ModelMetadataResponse: typing_extensions.TypeAlias = ModelMetadataResponse

@typing.final
class ModelInferRequest(google.protobuf.message.Message):
    """
    ModelInfer messages.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class InferInputTensor(google.protobuf.message.Message):
        """An input tensor for an inference request."""

        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        @typing.final
        class ParametersEntry(google.protobuf.message.Message):
            DESCRIPTOR: google.protobuf.descriptor.Descriptor

            KEY_FIELD_NUMBER: builtins.int
            VALUE_FIELD_NUMBER: builtins.int
            key: builtins.str
            @property
            def value(self) -> Global___InferParameter: ...
            def __init__(
                self,
                *,
                key: builtins.str = ...,
                value: Global___InferParameter | None = ...,
            ) -> None: ...
            def HasField(
                self, field_name: typing.Literal["value", b"value"]
            ) -> builtins.bool: ...
            def ClearField(
                self, field_name: typing.Literal["key", b"key", "value", b"value"]
            ) -> None: ...

        NAME_FIELD_NUMBER: builtins.int
        DATATYPE_FIELD_NUMBER: builtins.int
        SHAPE_FIELD_NUMBER: builtins.int
        PARAMETERS_FIELD_NUMBER: builtins.int
        CONTENTS_FIELD_NUMBER: builtins.int
        name: builtins.str
        """The tensor name."""
        datatype: builtins.str
        """The tensor data type."""
        @property
        def shape(
            self,
        ) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[
            builtins.int
        ]:
            """The tensor shape."""

        @property
        def parameters(
            self,
        ) -> google.protobuf.internal.containers.MessageMap[
            builtins.str, Global___InferParameter
        ]:
            """Optional inference input tensor parameters."""

        @property
        def contents(self) -> Global___InferTensorContents:
            """The input tensor data.
            This field must not be specified if tensor contents are being specified
            in ModelInferRequest.raw_input_contents.
            """

        def __init__(
            self,
            *,
            name: builtins.str = ...,
            datatype: builtins.str = ...,
            shape: collections.abc.Iterable[builtins.int] | None = ...,
            parameters: (
                collections.abc.Mapping[builtins.str, Global___InferParameter] | None
            ) = ...,
            contents: Global___InferTensorContents | None = ...,
        ) -> None: ...
        def HasField(
            self, field_name: typing.Literal["contents", b"contents"]
        ) -> builtins.bool: ...
        def ClearField(
            self,
            field_name: typing.Literal[
                "contents",
                b"contents",
                "datatype",
                b"datatype",
                "name",
                b"name",
                "parameters",
                b"parameters",
                "shape",
                b"shape",
            ],
        ) -> None: ...

    @typing.final
    class InferRequestedOutputTensor(google.protobuf.message.Message):
        """An output tensor requested for an inference request."""

        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        @typing.final
        class ParametersEntry(google.protobuf.message.Message):
            DESCRIPTOR: google.protobuf.descriptor.Descriptor

            KEY_FIELD_NUMBER: builtins.int
            VALUE_FIELD_NUMBER: builtins.int
            key: builtins.str
            @property
            def value(self) -> Global___InferParameter: ...
            def __init__(
                self,
                *,
                key: builtins.str = ...,
                value: Global___InferParameter | None = ...,
            ) -> None: ...
            def HasField(
                self, field_name: typing.Literal["value", b"value"]
            ) -> builtins.bool: ...
            def ClearField(
                self, field_name: typing.Literal["key", b"key", "value", b"value"]
            ) -> None: ...

        NAME_FIELD_NUMBER: builtins.int
        PARAMETERS_FIELD_NUMBER: builtins.int
        name: builtins.str
        """The tensor name."""
        @property
        def parameters(
            self,
        ) -> google.protobuf.internal.containers.MessageMap[
            builtins.str, Global___InferParameter
        ]:
            """Optional requested output tensor parameters."""

        def __init__(
            self,
            *,
            name: builtins.str = ...,
            parameters: (
                collections.abc.Mapping[builtins.str, Global___InferParameter] | None
            ) = ...,
        ) -> None: ...
        def ClearField(
            self,
            field_name: typing.Literal["name", b"name", "parameters", b"parameters"],
        ) -> None: ...

    @typing.final
    class ParametersEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        @property
        def value(self) -> Global___InferParameter: ...
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: Global___InferParameter | None = ...,
        ) -> None: ...
        def HasField(
            self, field_name: typing.Literal["value", b"value"]
        ) -> builtins.bool: ...
        def ClearField(
            self, field_name: typing.Literal["key", b"key", "value", b"value"]
        ) -> None: ...

    MODEL_NAME_FIELD_NUMBER: builtins.int
    MODEL_VERSION_FIELD_NUMBER: builtins.int
    ID_FIELD_NUMBER: builtins.int
    PARAMETERS_FIELD_NUMBER: builtins.int
    INPUTS_FIELD_NUMBER: builtins.int
    OUTPUTS_FIELD_NUMBER: builtins.int
    RAW_INPUT_CONTENTS_FIELD_NUMBER: builtins.int
    model_name: builtins.str
    """The name of the model to use for inferencing."""
    model_version: builtins.str
    """The version of the model to use for inference. If not given the
    server will choose a version based on the model and internal policy.
    """
    id: builtins.str
    """Optional identifier for the request. If specified will be
    returned in the response.
    """
    @property
    def parameters(
        self,
    ) -> google.protobuf.internal.containers.MessageMap[
        builtins.str, Global___InferParameter
    ]:
        """Optional inference parameters."""

    @property
    def inputs(
        self,
    ) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[
        Global___ModelInferRequest.InferInputTensor
    ]:
        """The input tensors for the inference."""

    @property
    def outputs(
        self,
    ) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[
        Global___ModelInferRequest.InferRequestedOutputTensor
    ]:
        """The requested output tensors for the inference. Optional, if not
        specified all outputs produced by the model will be returned.
        """

    @property
    def raw_input_contents(
        self,
    ) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[
        builtins.bytes
    ]:
        """The data contained in an input tensor can be represented in "raw" bytes
        form or in the repeated type that matches the tensor's data type. Using
        the "raw" bytes form will typically allow higher performance due to the
        way protobuf allocation and reuse interacts with GRPC. For example, see
        https://github.com/grpc/grpc/issues/23231.

        To use the raw representation 'raw_input_contents' must be initialized
        with data for each tensor in the same order as 'inputs'. For each tensor,
        the size of this content must match what is expected by the tensor's shape
        and data type. The raw data must be the flattened, one-dimensional,
        row-major order of the tensor elements without any stride or padding
        between the elements. Note that the FP16 and BF16 data types must be
        represented as raw content as there is no specific data type for a 16-bit
        float type.

        If this field is specified then InferInputTensor::contents must not be
        specified for any input tensor.
        """

    def __init__(
        self,
        *,
        model_name: builtins.str = ...,
        model_version: builtins.str = ...,
        id: builtins.str = ...,
        parameters: (
            collections.abc.Mapping[builtins.str, Global___InferParameter] | None
        ) = ...,
        inputs: (
            collections.abc.Iterable[Global___ModelInferRequest.InferInputTensor] | None
        ) = ...,
        outputs: (
            collections.abc.Iterable[
                Global___ModelInferRequest.InferRequestedOutputTensor
            ]
            | None
        ) = ...,
        raw_input_contents: collections.abc.Iterable[builtins.bytes] | None = ...,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "id",
            b"id",
            "inputs",
            b"inputs",
            "model_name",
            b"model_name",
            "model_version",
            b"model_version",
            "outputs",
            b"outputs",
            "parameters",
            b"parameters",
            "raw_input_contents",
            b"raw_input_contents",
        ],
    ) -> None: ...

Global___ModelInferRequest: typing_extensions.TypeAlias = ModelInferRequest

@typing.final
class ModelInferResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class InferOutputTensor(google.protobuf.message.Message):
        """An output tensor returned for an inference request."""

        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        @typing.final
        class ParametersEntry(google.protobuf.message.Message):
            DESCRIPTOR: google.protobuf.descriptor.Descriptor

            KEY_FIELD_NUMBER: builtins.int
            VALUE_FIELD_NUMBER: builtins.int
            key: builtins.str
            @property
            def value(self) -> Global___InferParameter: ...
            def __init__(
                self,
                *,
                key: builtins.str = ...,
                value: Global___InferParameter | None = ...,
            ) -> None: ...
            def HasField(
                self, field_name: typing.Literal["value", b"value"]
            ) -> builtins.bool: ...
            def ClearField(
                self, field_name: typing.Literal["key", b"key", "value", b"value"]
            ) -> None: ...

        NAME_FIELD_NUMBER: builtins.int
        DATATYPE_FIELD_NUMBER: builtins.int
        SHAPE_FIELD_NUMBER: builtins.int
        PARAMETERS_FIELD_NUMBER: builtins.int
        CONTENTS_FIELD_NUMBER: builtins.int
        name: builtins.str
        """The tensor name."""
        datatype: builtins.str
        """The tensor data type."""
        @property
        def shape(
            self,
        ) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[
            builtins.int
        ]:
            """The tensor shape."""

        @property
        def parameters(
            self,
        ) -> google.protobuf.internal.containers.MessageMap[
            builtins.str, Global___InferParameter
        ]:
            """Optional output tensor parameters."""

        @property
        def contents(self) -> Global___InferTensorContents:
            """The output tensor data.
            This field must not be specified if tensor contents are being specified
            in ModelInferResponse.raw_output_contents.
            """

        def __init__(
            self,
            *,
            name: builtins.str = ...,
            datatype: builtins.str = ...,
            shape: collections.abc.Iterable[builtins.int] | None = ...,
            parameters: (
                collections.abc.Mapping[builtins.str, Global___InferParameter] | None
            ) = ...,
            contents: Global___InferTensorContents | None = ...,
        ) -> None: ...
        def HasField(
            self, field_name: typing.Literal["contents", b"contents"]
        ) -> builtins.bool: ...
        def ClearField(
            self,
            field_name: typing.Literal[
                "contents",
                b"contents",
                "datatype",
                b"datatype",
                "name",
                b"name",
                "parameters",
                b"parameters",
                "shape",
                b"shape",
            ],
        ) -> None: ...

    @typing.final
    class ParametersEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        @property
        def value(self) -> Global___InferParameter: ...
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: Global___InferParameter | None = ...,
        ) -> None: ...
        def HasField(
            self, field_name: typing.Literal["value", b"value"]
        ) -> builtins.bool: ...
        def ClearField(
            self, field_name: typing.Literal["key", b"key", "value", b"value"]
        ) -> None: ...

    MODEL_NAME_FIELD_NUMBER: builtins.int
    MODEL_VERSION_FIELD_NUMBER: builtins.int
    ID_FIELD_NUMBER: builtins.int
    PARAMETERS_FIELD_NUMBER: builtins.int
    OUTPUTS_FIELD_NUMBER: builtins.int
    RAW_OUTPUT_CONTENTS_FIELD_NUMBER: builtins.int
    model_name: builtins.str
    """The name of the model used for inference."""
    model_version: builtins.str
    """The version of the model used for inference."""
    id: builtins.str
    """The id of the inference request if one was specified."""
    @property
    def parameters(
        self,
    ) -> google.protobuf.internal.containers.MessageMap[
        builtins.str, Global___InferParameter
    ]:
        """Optional inference response parameters."""

    @property
    def outputs(
        self,
    ) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[
        Global___ModelInferResponse.InferOutputTensor
    ]:
        """The output tensors holding inference results."""

    @property
    def raw_output_contents(
        self,
    ) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[
        builtins.bytes
    ]:
        """The data contained in an output tensor can be represented in "raw" bytes
        form or in the repeated type that matches the tensor's data type. Using
        the "raw" bytes form will typically allow higher performance due to the
        way protobuf allocation and reuse interacts with GRPC. For example, see
        https://github.com/grpc/grpc/issues/23231.

        To use the raw representation 'raw_output_contents' must be initialized
        with data for each tensor in the same order as 'outputs'. For each tensor,
        the size of this content must match what is expected by the tensor's shape
        and data type. The raw data must be the flattened, one-dimensional,
        row-major order of the tensor elements without any stride or padding
        between the elements. Note that the FP16 and BF16 data types must be
        represented as raw content as there is no specific data type for a 16-bit
        float type.

        If this field is specified then InferOutputTensor::contents must not be
        specified for any output tensor.
        """

    def __init__(
        self,
        *,
        model_name: builtins.str = ...,
        model_version: builtins.str = ...,
        id: builtins.str = ...,
        parameters: (
            collections.abc.Mapping[builtins.str, Global___InferParameter] | None
        ) = ...,
        outputs: (
            collections.abc.Iterable[Global___ModelInferResponse.InferOutputTensor]
            | None
        ) = ...,
        raw_output_contents: collections.abc.Iterable[builtins.bytes] | None = ...,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "id",
            b"id",
            "model_name",
            b"model_name",
            "model_version",
            b"model_version",
            "outputs",
            b"outputs",
            "parameters",
            b"parameters",
            "raw_output_contents",
            b"raw_output_contents",
        ],
    ) -> None: ...

Global___ModelInferResponse: typing_extensions.TypeAlias = ModelInferResponse

@typing.final
class InferParameter(google.protobuf.message.Message):
    """
    An inference parameter value.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    BOOL_PARAM_FIELD_NUMBER: builtins.int
    INT64_PARAM_FIELD_NUMBER: builtins.int
    STRING_PARAM_FIELD_NUMBER: builtins.int
    bool_param: builtins.bool
    """A boolean parameter value."""
    int64_param: builtins.int
    """An int64 parameter value."""
    string_param: builtins.str
    """A string parameter value."""
    def __init__(
        self,
        *,
        bool_param: builtins.bool = ...,
        int64_param: builtins.int = ...,
        string_param: builtins.str = ...,
    ) -> None: ...
    def HasField(
        self,
        field_name: typing.Literal[
            "bool_param",
            b"bool_param",
            "int64_param",
            b"int64_param",
            "parameter_choice",
            b"parameter_choice",
            "string_param",
            b"string_param",
        ],
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "bool_param",
            b"bool_param",
            "int64_param",
            b"int64_param",
            "parameter_choice",
            b"parameter_choice",
            "string_param",
            b"string_param",
        ],
    ) -> None: ...
    def WhichOneof(
        self, oneof_group: typing.Literal["parameter_choice", b"parameter_choice"]
    ) -> typing.Literal["bool_param", "int64_param", "string_param"] | None: ...

Global___InferParameter: typing_extensions.TypeAlias = InferParameter

@typing.final
class InferTensorContents(google.protobuf.message.Message):
    """
    The data contained in a tensor. For a given data type the
    tensor contents can be represented in "raw" bytes form or in
    the repeated type that matches the tensor's data type. Protobuf
    oneof is not used because oneofs cannot contain repeated fields.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    BOOL_CONTENTS_FIELD_NUMBER: builtins.int
    INT_CONTENTS_FIELD_NUMBER: builtins.int
    INT64_CONTENTS_FIELD_NUMBER: builtins.int
    UINT_CONTENTS_FIELD_NUMBER: builtins.int
    UINT64_CONTENTS_FIELD_NUMBER: builtins.int
    FP32_CONTENTS_FIELD_NUMBER: builtins.int
    FP64_CONTENTS_FIELD_NUMBER: builtins.int
    BYTES_CONTENTS_FIELD_NUMBER: builtins.int
    @property
    def bool_contents(
        self,
    ) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[
        builtins.bool
    ]:
        """Representation for BOOL data type. The size must match what is
        expected by the tensor's shape. The contents must be the flattened,
        one-dimensional, row-major order of the tensor elements.
        """

    @property
    def int_contents(
        self,
    ) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]:
        """Representation for INT8, INT16, and INT32 data types. The size
        must match what is expected by the tensor's shape. The contents
        must be the flattened, one-dimensional, row-major order of the
        tensor elements.
        """

    @property
    def int64_contents(
        self,
    ) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]:
        """Representation for INT64 data types. The size must match what
        is expected by the tensor's shape. The contents must be the
        flattened, one-dimensional, row-major order of the tensor elements.
        """

    @property
    def uint_contents(
        self,
    ) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]:
        """Representation for UINT8, UINT16, and UINT32 data types. The size
        must match what is expected by the tensor's shape. The contents
        must be the flattened, one-dimensional, row-major order of the
        tensor elements.
        """

    @property
    def uint64_contents(
        self,
    ) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]:
        """Representation for UINT64 data types. The size must match what
        is expected by the tensor's shape. The contents must be the
        flattened, one-dimensional, row-major order of the tensor elements.
        """

    @property
    def fp32_contents(
        self,
    ) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[
        builtins.float
    ]:
        """Representation for FP32 data type. The size must match what is
        expected by the tensor's shape. The contents must be the flattened,
        one-dimensional, row-major order of the tensor elements.
        """

    @property
    def fp64_contents(
        self,
    ) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[
        builtins.float
    ]:
        """Representation for FP64 data type. The size must match what is
        expected by the tensor's shape. The contents must be the flattened,
        one-dimensional, row-major order of the tensor elements.
        """

    @property
    def bytes_contents(
        self,
    ) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[
        builtins.bytes
    ]:
        """Representation for BYTES data type. The size must match what is
        expected by the tensor's shape. The contents must be the flattened,
        one-dimensional, row-major order of the tensor elements.
        """

    def __init__(
        self,
        *,
        bool_contents: collections.abc.Iterable[builtins.bool] | None = ...,
        int_contents: collections.abc.Iterable[builtins.int] | None = ...,
        int64_contents: collections.abc.Iterable[builtins.int] | None = ...,
        uint_contents: collections.abc.Iterable[builtins.int] | None = ...,
        uint64_contents: collections.abc.Iterable[builtins.int] | None = ...,
        fp32_contents: collections.abc.Iterable[builtins.float] | None = ...,
        fp64_contents: collections.abc.Iterable[builtins.float] | None = ...,
        bytes_contents: collections.abc.Iterable[builtins.bytes] | None = ...,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "bool_contents",
            b"bool_contents",
            "bytes_contents",
            b"bytes_contents",
            "fp32_contents",
            b"fp32_contents",
            "fp64_contents",
            b"fp64_contents",
            "int64_contents",
            b"int64_contents",
            "int_contents",
            b"int_contents",
            "uint64_contents",
            b"uint64_contents",
            "uint_contents",
            b"uint_contents",
        ],
    ) -> None: ...

Global___InferTensorContents: typing_extensions.TypeAlias = InferTensorContents

@typing.final
class ModelRepositoryParameter(google.protobuf.message.Message):
    """
    Messages for the Repository API

    NOTE: These messages used to exist previously on a different protobuf
    definition. However, they have now been merged with the main
    GRPCInferenceService.

    An model repository parameter value.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    BOOL_PARAM_FIELD_NUMBER: builtins.int
    INT64_PARAM_FIELD_NUMBER: builtins.int
    STRING_PARAM_FIELD_NUMBER: builtins.int
    BYTES_PARAM_FIELD_NUMBER: builtins.int
    bool_param: builtins.bool
    """A boolean parameter value."""
    int64_param: builtins.int
    """An int64 parameter value."""
    string_param: builtins.str
    """A string parameter value."""
    bytes_param: builtins.bytes
    """A bytes parameter value."""
    def __init__(
        self,
        *,
        bool_param: builtins.bool = ...,
        int64_param: builtins.int = ...,
        string_param: builtins.str = ...,
        bytes_param: builtins.bytes = ...,
    ) -> None: ...
    def HasField(
        self,
        field_name: typing.Literal[
            "bool_param",
            b"bool_param",
            "bytes_param",
            b"bytes_param",
            "int64_param",
            b"int64_param",
            "parameter_choice",
            b"parameter_choice",
            "string_param",
            b"string_param",
        ],
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "bool_param",
            b"bool_param",
            "bytes_param",
            b"bytes_param",
            "int64_param",
            b"int64_param",
            "parameter_choice",
            b"parameter_choice",
            "string_param",
            b"string_param",
        ],
    ) -> None: ...
    def WhichOneof(
        self, oneof_group: typing.Literal["parameter_choice", b"parameter_choice"]
    ) -> (
        typing.Literal["bool_param", "int64_param", "string_param", "bytes_param"]
        | None
    ): ...

Global___ModelRepositoryParameter: typing_extensions.TypeAlias = (
    ModelRepositoryParameter
)

@typing.final
class RepositoryIndexRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    REPOSITORY_NAME_FIELD_NUMBER: builtins.int
    READY_FIELD_NUMBER: builtins.int
    repository_name: builtins.str
    """The name of the repository. If empty the index is returned
    for all repositories.
    """
    ready: builtins.bool
    """If true return only models currently ready for inferencing."""
    def __init__(
        self,
        *,
        repository_name: builtins.str = ...,
        ready: builtins.bool = ...,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "ready", b"ready", "repository_name", b"repository_name"
        ],
    ) -> None: ...

Global___RepositoryIndexRequest: typing_extensions.TypeAlias = RepositoryIndexRequest

@typing.final
class RepositoryIndexResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class ModelIndex(google.protobuf.message.Message):
        """Index entry for a model."""

        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        NAME_FIELD_NUMBER: builtins.int
        VERSION_FIELD_NUMBER: builtins.int
        STATE_FIELD_NUMBER: builtins.int
        REASON_FIELD_NUMBER: builtins.int
        name: builtins.str
        """The name of the model."""
        version: builtins.str
        """The version of the model."""
        state: builtins.str
        """The state of the model."""
        reason: builtins.str
        """The reason, if any, that the model is in the given state."""
        def __init__(
            self,
            *,
            name: builtins.str = ...,
            version: builtins.str = ...,
            state: builtins.str = ...,
            reason: builtins.str = ...,
        ) -> None: ...
        def ClearField(
            self,
            field_name: typing.Literal[
                "name",
                b"name",
                "reason",
                b"reason",
                "state",
                b"state",
                "version",
                b"version",
            ],
        ) -> None: ...

    MODELS_FIELD_NUMBER: builtins.int
    @property
    def models(
        self,
    ) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[
        Global___RepositoryIndexResponse.ModelIndex
    ]:
        """An index entry for each model."""

    def __init__(
        self,
        *,
        models: (
            collections.abc.Iterable[Global___RepositoryIndexResponse.ModelIndex] | None
        ) = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["models", b"models"]) -> None: ...

Global___RepositoryIndexResponse: typing_extensions.TypeAlias = RepositoryIndexResponse

@typing.final
class RepositoryModelLoadRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class ParametersEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        @property
        def value(self) -> Global___ModelRepositoryParameter: ...
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: Global___ModelRepositoryParameter | None = ...,
        ) -> None: ...
        def HasField(
            self, field_name: typing.Literal["value", b"value"]
        ) -> builtins.bool: ...
        def ClearField(
            self, field_name: typing.Literal["key", b"key", "value", b"value"]
        ) -> None: ...

    REPOSITORY_NAME_FIELD_NUMBER: builtins.int
    MODEL_NAME_FIELD_NUMBER: builtins.int
    PARAMETERS_FIELD_NUMBER: builtins.int
    repository_name: builtins.str
    """The name of the repository to load from. If empty the model
    is loaded from any repository.
    """
    model_name: builtins.str
    """The name of the model to load, or reload."""
    @property
    def parameters(
        self,
    ) -> google.protobuf.internal.containers.MessageMap[
        builtins.str, Global___ModelRepositoryParameter
    ]:
        """Optional model repository request parameters."""

    def __init__(
        self,
        *,
        repository_name: builtins.str = ...,
        model_name: builtins.str = ...,
        parameters: (
            collections.abc.Mapping[builtins.str, Global___ModelRepositoryParameter]
            | None
        ) = ...,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "model_name",
            b"model_name",
            "parameters",
            b"parameters",
            "repository_name",
            b"repository_name",
        ],
    ) -> None: ...

Global___RepositoryModelLoadRequest: typing_extensions.TypeAlias = (
    RepositoryModelLoadRequest
)

@typing.final
class RepositoryModelLoadResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___RepositoryModelLoadResponse: typing_extensions.TypeAlias = (
    RepositoryModelLoadResponse
)

@typing.final
class RepositoryModelUnloadRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class ParametersEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        @property
        def value(self) -> Global___ModelRepositoryParameter: ...
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: Global___ModelRepositoryParameter | None = ...,
        ) -> None: ...
        def HasField(
            self, field_name: typing.Literal["value", b"value"]
        ) -> builtins.bool: ...
        def ClearField(
            self, field_name: typing.Literal["key", b"key", "value", b"value"]
        ) -> None: ...

    REPOSITORY_NAME_FIELD_NUMBER: builtins.int
    MODEL_NAME_FIELD_NUMBER: builtins.int
    PARAMETERS_FIELD_NUMBER: builtins.int
    repository_name: builtins.str
    """The name of the repository from which the model was originally
    loaded. If empty the repository is not considered.
    """
    model_name: builtins.str
    """The name of the model to unload."""
    @property
    def parameters(
        self,
    ) -> google.protobuf.internal.containers.MessageMap[
        builtins.str, Global___ModelRepositoryParameter
    ]:
        """Optional model repository request parameters."""

    def __init__(
        self,
        *,
        repository_name: builtins.str = ...,
        model_name: builtins.str = ...,
        parameters: (
            collections.abc.Mapping[builtins.str, Global___ModelRepositoryParameter]
            | None
        ) = ...,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "model_name",
            b"model_name",
            "parameters",
            b"parameters",
            "repository_name",
            b"repository_name",
        ],
    ) -> None: ...

Global___RepositoryModelUnloadRequest: typing_extensions.TypeAlias = (
    RepositoryModelUnloadRequest
)

@typing.final
class RepositoryModelUnloadResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___RepositoryModelUnloadResponse: typing_extensions.TypeAlias = (
    RepositoryModelUnloadResponse
)
