# @generated by generate_proto_mypy_stubs.py.  Do not edit!
import sys
from google.protobuf.descriptor import (
    Descriptor as google___protobuf___descriptor___Descriptor,
    FileDescriptor as google___protobuf___descriptor___FileDescriptor,
)

from google.protobuf.internal.containers import (
    RepeatedCompositeFieldContainer as google___protobuf___internal___containers___RepeatedCompositeFieldContainer,
)

from google.protobuf.message import (
    Message as google___protobuf___message___Message,
)

from typing import (
    Iterable as typing___Iterable,
    Optional as typing___Optional,
    Text as typing___Text,
)

from typing_extensions import (
    Literal as typing_extensions___Literal,
)

builtin___bool = bool
builtin___bytes = bytes
builtin___float = float
builtin___int = int

DESCRIPTOR: google___protobuf___descriptor___FileDescriptor = ...

class RepositoryIndexRequest(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    repository_name: typing___Text = ...
    ready: builtin___bool = ...
    def __init__(
        self,
        *,
        repository_name: typing___Optional[typing___Text] = None,
        ready: typing___Optional[builtin___bool] = None,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing_extensions___Literal[
            "ready", b"ready", "repository_name", b"repository_name"
        ],
    ) -> None: ...

type___RepositoryIndexRequest = RepositoryIndexRequest

class RepositoryIndexResponse(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    class ModelIndex(google___protobuf___message___Message):
        DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
        name: typing___Text = ...
        version: typing___Text = ...
        state: typing___Text = ...
        reason: typing___Text = ...
        def __init__(
            self,
            *,
            name: typing___Optional[typing___Text] = None,
            version: typing___Optional[typing___Text] = None,
            state: typing___Optional[typing___Text] = None,
            reason: typing___Optional[typing___Text] = None,
        ) -> None: ...
        def ClearField(
            self,
            field_name: typing_extensions___Literal[
                "name",
                b"name",
                "reason",
                b"reason",
                "state",
                b"state",
                "version",
                b"version",
            ],
        ) -> None: ...
    type___ModelIndex = ModelIndex
    @property
    def models(
        self,
    ) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[
        type___RepositoryIndexResponse.ModelIndex
    ]: ...
    def __init__(
        self,
        *,
        models: typing___Optional[
            typing___Iterable[type___RepositoryIndexResponse.ModelIndex]
        ] = None,
    ) -> None: ...
    def ClearField(
        self, field_name: typing_extensions___Literal["models", b"models"]
    ) -> None: ...

type___RepositoryIndexResponse = RepositoryIndexResponse

class RepositoryModelLoadRequest(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    repository_name: typing___Text = ...
    model_name: typing___Text = ...
    def __init__(
        self,
        *,
        repository_name: typing___Optional[typing___Text] = None,
        model_name: typing___Optional[typing___Text] = None,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing_extensions___Literal[
            "model_name", b"model_name", "repository_name", b"repository_name"
        ],
    ) -> None: ...

type___RepositoryModelLoadRequest = RepositoryModelLoadRequest

class RepositoryModelLoadResponse(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    def __init__(
        self,
    ) -> None: ...

type___RepositoryModelLoadResponse = RepositoryModelLoadResponse

class RepositoryModelUnloadRequest(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    repository_name: typing___Text = ...
    model_name: typing___Text = ...
    def __init__(
        self,
        *,
        repository_name: typing___Optional[typing___Text] = None,
        model_name: typing___Optional[typing___Text] = None,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing_extensions___Literal[
            "model_name", b"model_name", "repository_name", b"repository_name"
        ],
    ) -> None: ...

type___RepositoryModelUnloadRequest = RepositoryModelUnloadRequest

class RepositoryModelUnloadResponse(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    def __init__(
        self,
    ) -> None: ...

type___RepositoryModelUnloadResponse = RepositoryModelUnloadResponse
