# generated by datamodel-codegen:
#   filename:  model_repository.yaml

from __future__ import annotations

from enum import Enum
from typing import List, Optional

from pydantic import Field, RootModel

from .base import BaseModel


class RepositoryIndexRequest(BaseModel):
    ready: Optional[bool] = None


class State(Enum):
    UNKNOWN = "UNKNOWN"
    READY = "READY"
    UNAVAILABLE = "UNAVAILABLE"
    LOADING = "LOADING"
    UNLOADING = "UNLOADING"


class RepositoryIndexResponseItem(BaseModel):
    name: str
    version: Optional[str] = None
    state: State
    reason: str


class RepositoryIndexResponse(RootModel[List[RepositoryIndexResponseItem]]):
    root: List[RepositoryIndexResponseItem] = Field(
        ..., title="RepositoryIndexResponse"
    )

    def __iter__(self):
        return iter(self.root)

    def __getitem__(self, idx):
        return self.root[idx]

    def __len__(self):
        return len(self.root)


class RepositoryLoadErrorResponse(BaseModel):
    error: Optional[str] = None


class RepositoryUnloadErrorResponse(BaseModel):
    error: Optional[str] = None
