apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: json-hello-world
spec:
  predictors:
    - name: default
      annotations:
        seldon.io/no-engine: "true"
      graph:
        name: json-server
        type: MODEL
      componentSpecs:
        - spec:
            containers:
              - name: json-server
                image: my-custom-json-server
                ports:
                  - containerPort: 8080
                    name: http
                    protocol: TCP
                  - containerPort: 8081
                    name: grpc
                    protocol: TCP
